#
# Copyright 2021 Graviti. Licensed under MIT License.
#

---
version: 2

formats:
  - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements_docs.txt
    - requirements: requirements.txt
