#
# Copyright 2021 Graviti. Licensed under MIT License.
#

---
name: Integration Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    env:
      CACHE_KEY: >-
        integration-test-${{ matrix.os }}-${{ matrix.python-version }}-
        ${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements_test.txt') }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Cache python ${{ matrix.python-version }} in ubuntu
        if: "matrix.os == 'ubuntu-18.04'"
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python/${{ matrix.python-version }}
          key: ${{ CACHE_KEY }}

      - name: Cache python ${{ matrix.python-version }} in macos
        if: "matrix.os == 'macos-10.15'"
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/Python/${{ matrix.python-version }}
          key: ${{ CACHE_KEY }}

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt

      - name: Run pytest
        run: pytest tests --accesskey ${{ secrets.accesskey }} --url ${{ secrets.url }}
